template = ShipTemplate():setName("S.S. Bossman"):setClass("Frigate", "Diplomatic Gunship"):setModel("battleship_destroyer_1_upgraded"):setType(“playership”)
template:setDescription([[The S.S. Bossman is considered an intergalacticdestroyercruiserdiplomatictransportlightheavyadvancedgun
missileshipplatformarcon5000systemartemis/apollo hybrid ship. It’s high range and accuracy with phasers and missiles make it a formidable opponent]])
template:setRadarTrace("radar_adv_striker.png")
template:setHull(500)
template:setShields(300, 300)
template:setSpeed(130, 16, 10)
template:setWarpSpeed(700)
template:setCombatManeuver(400, 400)
template:setBeam(0, 40, 170, 1200.0, 1.0, 1)
template:setBeam(1, 40, 190, 1200.0, 1.0, 1)
template:setBeam(2, 40, 10, 1200.0, 1.0, 1)
template:setBeam(3, 40, 350, 1200.0, 1.0, 1)
template:setTubes(10, 20.0)
--set tube directions
template:setTubeDirection(1, 338)
template:setTubeDirection(2, 22)
template:setTubeDirection(3, 315)
template:setTubeDirection(4, 45)
template:setTubeDirection(5, 80)
template:setTubeDirection(6, 280)
template:setTubeDirection(7, 100)
template:setTubeDirection(8, 260)
template:setTubeDirection(9, 180)
template:setTubeDirection(10, 180):setWeaponTubeExclusiveFor(10, "Mine")
template:setWeaponStorage("Homing", 26)
template:setWeaponStorage("EMP", 10)
template:setWeaponStorage("HVLI", 20)
template:setWeaponStorage("Nuke", 4)
template:setWeaponStorage("Mine", 12)
template:setProbeStorage(10)

variation:setRepairCrewCount(8)

variation:addRoom(1, 0, 6, 1)
variation:addRoom(1, 5, 6, 1)
variation:addRoomSystem(0, 1, 2, 2, "RearShield")
variation:addRoomSystem(0, 3, 2, 2, "MissileSystem")
variation:addRoomSystem(2, 1, 2, 2, "Beamweapons")
variation:addRoomSystem(2, 3, 2, 2, "Reactor")
variation:addRoomSystem(4, 1, 2, 2, "Warp")
variation:addRoomSystem(4, 3, 2, 2, "JumpDrive")
variation:addRoomSystem(6, 1, 2, 2, "Impulse")
variation:addRoomSystem(6, 3, 2, 2, "Maneuver")
variation:addRoomSystem(8, 2, 2, 2, "FrontShield")

variation:addDoor(1, 1, true)
variation:addDoor(3, 1, true)
variation:addDoor(4, 1, true)
variation:addDoor(6, 1, true)

variation:addDoor(4, 3, true)
variation:addDoor(5, 3, true)

variation:addDoor(8, 2, false)
variation:addDoor(8, 3, false)

variation:addDoor(1, 5, true)
variation:addDoor(2, 5, true)
variation:addDoor(5, 5, true)
variation:addDoor(6, 5, true)
